# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

url:  http://emenendez.github.io
name: emenendez<span class="github">.github.io</span>
description: 'Thoughts on wildland search & rescue.'
author:
  name: Eric Menendez
  email: ericmenendez@gmail.com
  url: https://github.com/emenendez
  twitter:
    url: https://twitter.com/ericrmenendez
    user: '@ericrmenendez'

license:
  name: CC-BY-SA 4.0
  url:  http://creativecommons.org/licenses/by-sa/4.0/

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: false
show_drafts: false

# Markdown library
markdown: kramdown
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: pygments

# Sass
sass:
  style: :compressed

# Permalinks
permalink:        /:title/

# Custom vars
github:
  repo:           https://github.com/emenendez/emenendez.github.io
